### ISSUE TITLE
Plugin crashes on startup

### ISSUE THREAD

**Issue by rhuitl** [afrimberger/okularplugin#2]
Most of the time, however not always, the plugin crashes right after opening a PDF file. Here's the trace:

GNU gdb (Ubuntu/Linaro 7.4-2012.04-0ubuntu2) 7.4-2012.04
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
For bug reporting instructions, please see:
http://bugs.launchpad.net/gdb-linaro/...
Reading symbols from /usr/lib/chromium-browser/chromium-browser...(no debugging symbols found)...done.
(gdb) r
Starting program: /usr/lib/chromium-browser/chromium-browser --type=plugin --plugin-path=/usr/lib/chromium-browser/plugins/libokularplugin.so --lang=de --channel=11194.23.1094862719
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffed253700 (LWP 11478)]

Program received signal SIGSEGV, Segmentation fault.
0x00007fffead0f36e in NPP_Write (buffer=<optimized out>, len=32768,
    stream=0x555559bf2378, instance=<optimized out>)
    at /home/robert/devel/okularplugin/qtbrowserplugin/qtbrowserplugin.cpp:1123
1123        This->bindable->readProgress(len, stream->end);
(gdb) bt
#0  0x00007fffead0f36e in NPP_Write (buffer=<optimized out>, len=32768,

```
stream=0x555559bf2378, instance=<optimized out>)
at /home/robert/devel/okularplugin/qtbrowserplugin/qtbrowserplugin.cpp:1123
```
#1  NPP_Write (instance=<optimized out>, stream=0x555559bf2378, len=32768,

```
buffer=<optimized out>)
at /home/robert/devel/okularplugin/qtbrowserplugin/qtbrowserplugin.cpp:1114
```
#2  0x00005555577c719c in ?? ()
#3  0x00005555577c777d in ?? ()
#4  0x00005555577c7960 in ?? ()
#5  0x000055555778f581 in ?? ()
#6  0x0000555557b3ea20 in ?? ()
#7  0x0000555556a6e333 in ?? ()
#8  0x0000555557e13dd8 in ?? ()
#9  0x0000555557b3b8b5 in ?? ()
#10 0x000055555635e0a9 in ?? ()
#11 0x00005555563616fb in ?? ()
#12 0x0000555556361d03 in ?? ()
#13 0x000055555638e119 in ?? ()
#14 0x000055555638e15d in ?? ()
#15 0x00007ffff697cd53 in g_main_context_dispatch ()

   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff697d0a0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007ffff697d164 in g_main_context_iteration ()

   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x000055555638de2f in ?? ()
#19 0x000055555635d810 in ?? ()
#20 0x0000555557b3a4b4 in ?? ()
#21 0x000055555632a378 in ?? ()
#22 0x0000555555ac7968 in ?? ()
#23 0x0000555555ac5e06 in ?? ()
#24 0x00007ffff202b76d in __libc_start_main (main=0x555555ac5e00, argc=5,

```
ubp_av=0x7fffffffddc8, init=<optimized out>, fini=<optimized out>,
rtld_fini=<optimized out>, stack_end=0x7fffffffddb8) at libc-start.c:226
```
#25 0x0000555555ac786d in ?? ()
#26 0x00007fffffffddb8 in ?? ()
#27 0x000000000000001c in ?? ()
#28 0x0000000000000005 in ?? ()
#29 0x00007fffffffe13e in ?? ()
#30 0x0000000000000000 in ?? ()

(gdb) print This
$1 = (QtNPInstance *) 0x555559c99b00
(gdb) print This->bindable
$2 = (QtNPBindable *) 0x0

This is on Ubuntu 12.04 (64 bit) with Chromium 18.0.1025.168 and today's git code of okularplugin. Same problem with Chrome 21.0.1180.81. Please let me know if you need more information.

**Comment by afrimberger** [comment]
What desktop environment are you using?

Could be related to a race condition that happens if widget creation takes too long. However I commited a patch to the master branch that should fix the problem. Can you please confirm whether it works for you?

**Comment by rhuitl** [comment]
I'm using KDE 4.8.4. Unfortunately, your patch does not fix the problem, it still crashes because This->bindable is 0. I tried this patch

```
     QtNPInstance *This = (QtNPInstance*)instance->pdata;
+    if(!This->bindable)
+        return NPERR_INVALID_INSTANCE_ERROR;
+
     // this should not be called, as we always demand a download
```

which prevents the crash, however no document is loaded.

**Comment by afrimberger** [comment]
Well, the idea of my patch was to check for instance->pdata->bindable != NULL... exactly as you assumed ;-).

I think the problem is that in some cases the widget is created after the download starts. This is the case if the following patch works for you:

``` diff
diff --git a/qtbrowserplugin/qtbrowserplugin.cpp b/qtbrowserplugin/qtbrowserplugin.cpp
index a675b8e..352b2aa 100644
--- a/qtbrowserplugin/qtbrowserplugin.cpp
+++ b/qtbrowserplugin/qtbrowserplugin.cpp
@@ -1113,14 +1113,16 @@ NPP_WriteReady(NPP, NPStream *stream)
 extern "C" KDE_EXPORT  int32
 NPP_Write(NPP instance, NPStream *stream, int32 /*offset*/, int32 len, void *buffer)
 {
-    if (!instance || !stream || !stream->pdata || !instance->pdata)
+    if (!instance || !stream || !stream->pdata)
         return NPERR_INVALID_INSTANCE_ERROR;

     QtNPInstance *This = (QtNPInstance*)instance->pdata;
     // this should not be called, as we always demand a download
     QtNPStream *qstream = (QtNPStream*)stream->pdata;
     QByteArray data((const char*)buffer, len); // make deep copy
-    This->bindable->readProgress(len, stream->end);
+    if (This->bindable != NULL) {
+      This->bindable->readProgress(len, stream->end);
+    }
     qstream->buffer += data;

     return len;
```

The patch also affects the correctness of the progress bar. So don't be surprised if it doesn't work as expected. I will commit a better solution if the above patch fixes your problem.

**Comment by rhuitl** [comment]
Yes I think the crashes are gone with this patch!

**Comment by rhuitl** [comment]
Here's another crash, happens when I click PDF link -> new tab with PDF opens -> close tab -> click link again -> tab opens (same plugin process) -> close tab -> crash

```

Program received signal SIGSEGV, Segmentation fault.
0x00007fffe8f5bb8a in QObject::~QObject() ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
(gdb) bt
#0  0x00007fffe8f5bb8a in QObject::~QObject() ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#1  0x00007fffea208829 in QHBoxLayout::~QHBoxLayout() ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#2  0x00007fffea24660f in QWidget::~QWidget() ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#3  0x00007fffea29bc09 in QX11EmbedWidget::~QX11EmbedWidget() ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#4  0x00007fffead1417a in qtns_destroy (This=0x555559c99080)
    at /home/robert/devel/okularplugin/qtbrowserplugin/qtbrowserplugin_x11.cpp:84
#5  0x00007fffead0f119 in NPP_Destroy (instance=0x55555a37e790)
    at /home/robert/devel/okularplugin/qtbrowserplugin/qtbrowserplugin.cpp:971
#6  NPP_Destroy (instance=0x55555a37e790)
    at /home/robert/devel/okularplugin/qtbrowserplugin/qtbrowserplugin.cpp:956
#7  0x0000555557785f9d in ?? ()
#8  0x0000555557fb45a9 in ?? ()
#9  0x0000555557fb4c3c in ?? ()
#10 0x0000555557fb4d39 in ?? ()
#11 0x0000555557fb4358 in ?? ()
#12 0x0000555557b3dd57 in ?? ()
#13 0x0000555557b3df19 in ?? ()
#14 0x0000555557b3c779 in ?? ()
#15 0x0000555557b3c470 in ?? ()
#16 0x0000555557e14637 in ?? ()
#17 0x0000555557b3b8b5 in ?? ()
#18 0x0000555556a9ac9a in ?? ()
#19 0x000055555635e0a9 in ?? ()
#20 0x00005555563616fb in ?? ()
#21 0x0000555556361d03 in ?? ()
#22 0x000055555638e119 in ?? ()
#23 0x000055555638e15d in ?? ()
#24 0x00007ffff697cd53 in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007ffff697d0a0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007ffff697d164 in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x000055555638de2f in ?? ()
#28 0x000055555635d810 in ?? ()
#29 0x0000555557b3a4b4 in ?? ()
#30 0x000055555632a378 in ?? ()
#31 0x0000555555ac7968 in ?? ()
#32 0x0000555555ac5e06 in ?? ()
#33 0x00007ffff202b76d in __libc_start_main (main=0x555555ac5e00, argc=5,
    ubp_av=0x7fffffffddb8, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7fffffffdda8) at libc-start.c:226
#34 0x0000555555ac786d in ?? ()
#35 0x00007fffffffdda8 in ?? ()
#36 0x000000000000001c in ?? ()
#37 0x0000000000000005 in ?? ()
#38 0x00007fffffffe12c in ?? ()
#39 0x0000000000000000 in ?? ()
```

**Comment by afrimberger** [comment]
Is this crash always reproducible for you? For me it isn't, worked in 20 out of 20 trials.

**Comment by rhuitl** [comment]
Yes 100 % reproducible but only when gdb is active, it seems... try this: start chromium using gdb for plugins
    chromium-browser --plugin-launcher='xterm -e gdb --args'

Browse to http://www.pdfpdf.com/samples.html, click one of the PDFs which open a new tab, close it, and open it again.

**Comment by afrimberger** [comment]
Seems like this bug is only triggered when the page itself opens the PDF in a new tab. I couldn't reproduce it with PDFs opened by myself in a new tab. By the way it doesn't matter whether gdb is attached to the plugin process.

What I found out so far: 
- The bug happens in Qt or in qtbrowserplugin, which hides all that NPAPI stuff from Qt. It is also possible that it is triggered by a combination of chromium (chrome not tested) and Qt. 
- The okularplugin related stuff is not responsible for that bug, because commenting it out doesn't solve the problem.

**Comment by rhuitl** [comment]
Good catch! With the latest patch, it doesn't crash anymore. Thank you André!
